name: recreate_branch

on:
  workflow_dispatch:
    inputs:
      branch_choice:
        description: Choose a common branch (used if free text empty)
        required: true
        type: choice
        default: main
        options:
          - release/qa
      branch_name:
        description: Or type a custom branch name (overrides choice if set)
        required: false
        type: string

concurrency:
  group: recreate_branch

permissions:
  contents: write

jobs:
  recreate_branch:
    name: Recreate branch
    runs-on: ubuntu-latest
    environment:
      name: recreate-branch

    steps:
      - name: Resolve target branch
        env:
          BRANCH_NAME_INPUT: ${{ github.event.inputs.branch_name }}
          BRANCH_CHOICE_INPUT: ${{ github.event.inputs.branch_choice }}
        run: |
          TARGET_BRANCH="$BRANCH_NAME_INPUT"
          if [ -z "$TARGET_BRANCH" ]; then
            TARGET_BRANCH="$BRANCH_CHOICE_INPUT"
          fi
          echo "Target branch: $TARGET_BRANCH"
          echo "BRANCH_TO_RECREATE=$TARGET_BRANCH" >> "$GITHUB_ENV"

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "DWH QA github-action"
          git config user.email "github-actions@github.com"

      - name: Recreate branch
        run: |
          git checkout main
          git pull --rebase
          git branch -d "$BRANCH_TO_RECREATE" || true
          git push origin --delete "$BRANCH_TO_RECREATE" || true
          git checkout main
          git checkout -b "$BRANCH_TO_RECREATE"
          git push origin -u "$BRANCH_TO_RECREATE"


