name: Generate Version in test_release_tag

on:
  workflow_dispatch:

jobs:
  set-version:
    name: Call Shared Version Generator
    uses: oviva-ag/actions/.github/workflows/set-version.yml@main
    with:
      name: test_release_tag
      dev_mode: false
    secrets:
      GH_CI_PAT: ${{ secrets.GH_CI_PAT }}

  run-generator:
    name: Run Version Generator with Output
    needs: set-version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Setup Go (if needed)
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Download Latest Version Generator
        uses: oviva-ag/actions/download-go-release@main
        with:
          name: version-generator
          version: ${{ needs.set-version.outputs.version }}
          token: ${{ secrets.GH_CI_PAT }}

      - name: Make Binary Executable
        run: chmod +x version-generator-amd64

      - name: Run Version Generator
        env:
          INPUT_NAME: test_release_tag
          INPUT_REPOSITORYPATH: ${{ github.workspace }}
        run: ./version-generator-amd64
